### PR TITLE
Feat: add Lwjgl 3.4.1 for mc versions 26.1+

### PR DESCRIPTION
**Pull request by Taylen-chud**
Adds lwjgl 3.4.1 for mc versions 26.1+. 
If mc version is 1.21.11 and below it will use lwjgl 3.3.3.

# NOTE
* I haven’t actually tested this because I’m on iOS 27 so amethyst just dosent work at all but I’m pretty certain this would work but would be best to check/edit before merging if you did.

Also please tell me if I did something wrong or something you want changed like the folder names so I can edit them to what would make better sense.

* also I believe @alexytomi said to not add lwjglx in 3.4.1 or something like that but I did just incase it was something else.

I got the files from https://github.com/AngelAuraMC/lwjgl3

### CODE REVIEW

**Comment by alexytomi** [comment]
Which LWJGL build is this?

**Comment by Taylen-chud** [comment]
https://github.com/AngelAuraMC/lwjgl3/actions/runs/24789755284

File: JavaApp/libs/lwjgl-3.4.1/lwjgl-msdfgen.jar
Comment (alexytomi) [inline JavaApp/libs/lwjgl-3.4.1/lwjgl-msdfgen.jar:1]: Unused, remove

File: Natives/resources/Frameworks/libopenal.dylib
Comment (alexytomi) [inline Natives/resources/Frameworks/libopenal.dylib:1]: Why and what was this changed to?

File: Natives/resources/Frameworks/libshaderc.dylib
Comment (alexytomi) [inline Natives/resources/Frameworks/libshaderc.dylib:1]: Why and what was this changed to?

File: JavaApp/libs/lwjgl-3.4.1/lwjgl-lwjglx.jar
Comment (alexytomi) [inline JavaApp/libs/lwjgl-3.4.1/lwjgl-lwjglx.jar:1]: Unused, remove

**Review by alexytomi — DISMISSED** [review]

**Comment by Taylen-chud** [comment]
for openal I noticed it hasn’t been updated in awhile even if it does work fine I just thought it was okay to use the newer version from the build. When I did get amethyst to work on 26.1 it seemed fine I had no issues with my audio. For libshaderc I’m not sure why I decided to use the newer version because it sometimes crashed whenever I loaded the game. I’ll change libshaderc back to normal, remove lwjglx, msdfgen, but I think leaving open al should be fine I personally ran into no issues with it but if it is a problem please let me know.

**Comment by alexytomi** [comment]
Please note down where you got all the natives from. libshaderc update is fine so long as it's tested with zink and vulkanmod shaders.

**Comment by Taylen-chud** [comment]
Every native I replaced was from  https://github.com/AngelAuraMC/lwjgl3/actions/runs/24789755284. For libshaderc there was this really weird crash I got where the first time I would launch the game it would crash, but it was completely random at times. To prevent it from happening setting the resolution at anything around 75% and 100% seemed to fix it. 

That’s why I was hesitant on updating it. I did test it once with Vulkanmod and it seemed fine. I never did try it with beryl though unfortunately. Zink did work for me never had any issues with it.

 But considering people would probably get annoyed at their game crashing the first time they launch I think it’s best to just keep the original libshaderc.

**Comment by alexytomi** [comment]
If you updated libshaderc did you also update the lwjgl natives? Its always either all or nothing

**Comment by Taylen-chud** [comment]
Yes I did update all the other natives.

**Comment by Taylen-chud** [comment]
It’s kinda set up weird though. I have a folder called lwjgl34 and lwjgl33. Lwjgl 34 uses the new natives from your build and 33 uses the pre existing natives.

**Comment by alexytomi** [comment]
> It’s kinda set up weird though. I have a folder called lwjgl34 and lwjgl33. Lwjgl 34 uses the new natives from your build and 33 uses the pre existing natives.

You should update everything. This also shouldn't even launch as https://github.com/AngelAuraMC/Amethyst-iOS/blob/main/JavaApp/src/lwjgl/org/lwjgl/glfw/GLFW.java isn't updated to work with the breaking changes in https://github.com/AngelAuraMC/lwjgl3/commit/b84bec48c80f41249ecd0c07cf40f27b71506bd1

**Comment by Taylen-chud** [comment]
Okay I think everything should be fine now. I got the spirv Dylib from https://github.com/KhronosGroup/SPIRV-Cross/actions/runs/28792370694

**Comment by Taylen-chud** [comment]
Okay so I believe 1.21.11 and below dosent work anymore because the new glfw.java exposes something that just ends up crashing the game. I do have a vibe coded one that does work on both 1.21.11 and 26.1 but I’m assuming you guys really wouldn’t want that.

**Comment by Taylen-chud** [comment]
I’ll work on it soon, it shouldn’t take long since it should just be a couple lines to change.

File: Natives/JavaLauncher.m [hunk 1]
```diff
@@ -167,6 +168,13 @@ int launchJVM(NSString *username, id launchTarget, int width, int height, int mi
             defaultJRETag = @"1_17_newer";
         }
 
+        // Use LWJGL 3.4.1 for 26.1+, 3.3.3 for 1.21.11 and below
+        int mcMajorVersion = [launchTarget[@"id"] intValue];
```
Comment (khanhduytran0) [inline Natives/JavaLauncher.m]: Recommend changing this to checking LWJGL library version. See [this](https://github.com/AngelAuraMC/Amethyst-iOS/blob/64c5c9c44148d9cc7c7c4430940b8dcbe9331a44/Natives/MinecraftResourceUtils.m#L81-L88) for example.

**Comment by Taylen-chud** [comment]
I believe that's everything?

File: Natives/JavaLauncher.m (hunk 1 above)
Comment (alexytomi) [reply Natives/JavaLauncher.m]: Would like to add that LWJGL3ify 2.x would need this logic to run at all

**Comment by khanhduytran0** [comment]
There's an issue with building, `JavaApp/Makefile` don't have separate jobs to build separate lwjgl.jar yet

**Comment by Taylen-chud** [comment]
This should resolve the issue

**Comment by Taylen-chud** [comment]
For some reason this just dosent want to build anymore I get  this 

iOS/Natives/JavaLauncher.m:140:13: error: call to undeclared function 'task_set_exception_ports'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            task_set_exception_ports(mach_task_self(), EXC_MASK_ALL & ~EXC_MASK_BREAKPOINT, 0,
            ^
/Users/runner/work/Amethyst-iOS/Amethyst-iOS/Natives/JavaLauncher.m:140:38: error: call to undeclared function 'mach_task_self'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            task_set_exception_ports(mach_task_self(), EXC_MASK_ALL & ~EXC_MASK_BREAKPOINT, 0,
                                     ^
2 warnings and 4 errors generated.

**Comment by Taylen-chud** [comment]
I’ll fix it later I’m just busy today

**Comment by Taylen-chud** [comment]
Okay good news it builds now but the game crashes

[26.2 crash.txt](https://github.com/user-attachments/files/30068471/26.2.crash.txt)
[1.21.11 crash.txt](https://github.com/user-attachments/files/30068509/1.21.11.crash.txt)

**Comment by Taylen-chud** [comment]
[amethyst_halt0_dump.txt](https://github.com/user-attachments/files/30153822/amethyst_halt0_dump.txt)

I think I found it.

**Comment by Taylen-chud** [comment]
[amethyst_uncaught_exception.txt](https://github.com/user-attachments/files/30157407/amethyst_uncaught_exception.txt)
Okay now I have found the actual issue. @alexytomi  sorry to bother you but it seems the pre existing lwjgl.dylib dosent include libffi. Does one of the newer builds on the lwjgl3 fork include libffi?

**Comment by Taylen-chud** [comment]
Wait nvm I can just change GLFW.java

**Comment by alexytomi** [comment]
libffi isn't part of lwjgl dylibs, its a seperate dylib

**Comment by Taylen-chud** [comment]
That would make sense. Sorry for being dumb🫩

**Comment by Taylen-chud** [comment]
[latestlog.old.txt](https://github.com/user-attachments/files/30160859/latestlog.old.txt)

why is mobile glues failing now bruh

**Comment by Taylen-chud** [comment]
Haven’t tested this on 26.x but does get 1.21.11 to at least get further.

**Comment by Taylen-chud** [comment]
Should be fine I assume
